name: Android (Vulkan)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
    - name: Get krink DLC
      run: ./get_dlc
    - name: Compile
      run: Kinc/make android -g vulkan --kinc Kinc --from Tests/Empty --compile
